services:
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZTQxNDZmN2U1M2JmZDEwYTg1N2Q3M2QyNmYyZDMwZjciLCJ0IjoiMmNmM2VkMTItNTFhOS00NDliLWFhZTgtMWFkZmMxMThiM2VlIiwicyI6IlkyWTJOVFZoTURJdE9XWmhOUzAwTURBd0xXSmhPREF0T1dRNU5EUXlPVFUxTkdJdyJ9
  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./.env
  admin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
  web:
    depends_on:
      - mysql
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"